version: '3'
services:
  mongo_v:
    image: mongo:6.0
    container_name: mongo_v
    command: --bind_ip 0.0.0.0
    env_file:
      - .env_v
    volumes:
      - mongodbdata_v:/data/db
      - mongodbdata_v:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      network1:
        ipv4_address: ${MONGO_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  webui_v:
    image: docker_open5gs
    container_name: webui_v
    depends_on:
      - mongo_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=webui
    volumes:
      - ./webui:/mnt/webui
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "9998/tcp"
    ports:
      - "9998:9998/tcp"
    networks:
      network1:
        ipv4_address: ${WEBUI_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  nrf_v:
    image: docker_open5gs
    container_name: nrf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=nrf-2
    volumes:
      - ./nrf:/mnt/nrf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${NRF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  scp_v:
    image: docker_open5gs
    container_name: scp_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=scp-2
    volumes:
      - ./scp:/mnt/scp
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${SCP_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
      - "${AUSF_V_FQDN}:${AUSF_V_IP}"
      - "${UDM_V_FQDN}:${UDM_V_IP}"
  ausf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
    container_name: ausf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=ausf-2
    volumes:
      - ./ausf:/mnt/ausf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${AUSF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  udr_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - mongo_v
    container_name: udr_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=udr-2
    volumes:
      - ./udr:/mnt/udr
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${UDR_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  udm_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
    container_name: udm_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=udm-2
    volumes:
      - ./udm:/mnt/udm
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${UDM_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  smf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - amf_v
    container_name: smf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=smf-2
      - DEPLOY_MODE=5G
    volumes:
      - ./smf:/mnt/smf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "3868/udp"
      - "3868/tcp"
      - "3868/sctp"
      - "5868/udp"
      - "5868/tcp"
      - "5868/sctp"
      - "8805/udp"
      - "2123/udp"
      - "7777/tcp"
      - "9091/tcp"
    networks:
      network1:
        ipv4_address: ${SMF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  upf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - smf_v
    container_name: upf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=upf-2
    volumes:
      - ./upf:/mnt/upf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "2152/udp"
      - "8805/udp"
      - "9091/tcp"
    # ports:
    #   - "2152:2152/udp"
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      #- net.ipv6.conf.all.disable_ipv6=0
    networks:
      network1:
        ipv4_address: ${UPF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  amf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - ausf_v
      - udm_v
      - udr_v
      - pcf_v
      - bsf_v
    container_name: amf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=amf-2
    volumes:
      - ./amf:/mnt/amf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "38412/sctp"
      - "7777/tcp"
      - "9091/tcp"
    # ports:
    #   - "38412:38412/sctp"
    networks:
      network1:
        ipv4_address: ${AMF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  pcf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - mongo_v
    container_name: pcf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=pcf-2
    volumes:
      - ./pcf:/mnt/pcf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
      - "9091/tcp"
    networks:
      network1:
        ipv4_address: ${PCF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  bsf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - mongo_v
    container_name: bsf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=bsf-2
    volumes:
      - ./bsf:/mnt/bsf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${BSF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  nssf_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
      - mongo_v
    container_name: nssf_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=nssf-2
    volumes:
      - ./nssf:/mnt/nssf
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
    networks:
      network1:
        ipv4_address: ${NSSF_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
  sepp_v:
    image: docker_open5gs
    depends_on:
      - nrf_v
      - scp_v
    container_name: sepp_v
    env_file:
      - .env_v
    environment:
      - COMPONENT_NAME=sepp-2
    volumes:
      - ./sepp:/mnt/sepp
      - ./log:/open5gs/install/var/log/open5gs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "7777/tcp"
      - "7779/tcp"
      - "7780/tcp"
    # ports:
    #   - "7779:7779/tcp"
    #   - "7780:7780/tcp"
    networks:
      network1:
        ipv4_address: ${SEPP_IP}
    extra_hosts:
      - "${NRF_FQDN}:${NRF_IP}"
      - "${UDM_FQDN}:${UDM_IP}"
      - "${AUSF_FQDN}:${AUSF_IP}"
      - "${NRF_FQDN_BIS}:${NRF_IP}"
      - "${UDM_FQDN_BIS}:${UDM_IP}"
      - "${AUSF_FQDN_BIS}:${AUSF_IP}"
networks:
    network1:
      name: docker_open5gs_default
      external: true
#networks:
#  default:
#    ipam:
#      config:
#        - subnet: ${TEST_NETWORK}
volumes:
  mongodbdata_v: {}
