services:
  srsenb_zmq:
    image: docker_srslte
    container_name: srsenb_zmq
    stdin_open: true
    tty: true
    privileged: true
    volumes:
      - ./srslte:/mnt/srslte
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    environment:
      - COMPONENT_NAME=enb_zmq
    expose:
      - "36412/sctp"
      - "2152/udp"
      - "2000/tcp"
      - "2001/tcp"
    networks:
      default:
        ipv4_address: ${SRS_ENB_IP}
networks:
  default:
    external: true
    name: docker_open5gs_default
